rhesis-ai/rhesis

- apps/frontend/src/app/(protected)/test-runs/components/TestRunsGrid.tsx
> replaced empty columns in test run grid

- apps/backend/src/rhesis/backend/app/constants.py
- apps/backend/src/rhesis/backend/app/database.py
- apps/backend/src/rhesis/backend/app/schemas/test.py
- apps/backend/src/rhesis/backend/app/schemas/test_set.py
- apps/backend/src/rhesis/backend/app/services/bulk_defaults.json
- apps/backend/src/rhesis/backend/app/services/test.py
- apps/backend/src/rhesis/backend/app/services/test_set.py
- apps/backend/src/rhesis/backend/app/utils/crud_utils.py
- apps/backend/src/rhesis/backend/app/utils/model_utils.py
- apps/backend/src/rhesis/backend/app/utils/uuid_utils.py
This PR introduces changes from the `fix/test-set-bulk-creation` branch.
- Improving UUID handling for test bulk creation (3be94d9)
```
apps/backend/src/rhesis/backend/app/constants.py
apps/backend/src/rhesis/backend/app/database.py
apps/backend/src/rhesis/backend/app/schemas/test.py
apps/backend/src/rhesis/backend/app/schemas/test_set.py
apps/backend/src/rhesis/backend/app/services/bulk_defaults.json
apps/backend/src/rhesis/backend/app/services/test.py
apps/backend/src/rhesis/backend/app/services/test_set.py
apps/backend/src/rhesis/backend/app/utils/crud_utils.py
apps/backend/src/rhesis/backend/app/utils/model_utils.py
apps/backend/src/rhesis/backend/app/utils/uuid_utils.py
```
```
3be94d9 - Improving UUID handling for test bulk creation (Harry Cruz, 4 minutes ago)
```
> Fix: Test Set Bulk Creation

- apps/backend/src/rhesis/backend/app/services/stats.py
This PR introduces changes from the `fix/test-set-statistics` branch.
- fix: Improving status calculation (5056d58)
```
apps/backend/src/rhesis/backend/app/services/stats.py
```
```
5056d58 - fix: Improving status calculation (Harry Cruz, 18 seconds ago)
```
> Fix: Test Set Statistics

- apps/backend/src/rhesis/backend/app/database.py
- apps/backend/src/rhesis/backend/app/routers/test_set.py
- apps/backend/src/rhesis/backend/app/services/test.py
- apps/backend/src/rhesis/backend/app/services/test_set.py
- apps/backend/src/rhesis/backend/app/utils/crud_utils.py
- apps/backend/src/rhesis/backend/app/utils/model_utils.py
- apps/backend/src/rhesis/backend/app/utils/uuid_utils.py
- apps/backend/src/rhesis/backend/tasks/__init__.py
- apps/backend/src/rhesis/backend/tasks/base.py
- apps/backend/src/rhesis/backend/tasks/test_set.py
- apps/frontend/src/app/(protected)/tests/new-generated/components/GenerateTestsStepper.tsx
- apps/frontend/src/types/api-client.d.ts
- apps/frontend/src/utils/api-client/interfaces/test-set.ts
- apps/frontend/src/utils/api-client/test-sets-client.ts
- sdk/src/rhesis/sdk/synthesizers/__init__.py
- sdk/src/rhesis/sdk/synthesizers/assets/prompt_synthesizer.md
- sdk/src/rhesis/sdk/synthesizers/factory.py
This PR introduces changes from the `feature/worker-generation` branch.
- Task infrastructure for test generation (1c25c05)
- Backing utilities for test generation task (450ed58)
- Adding debuging to database utilities (36013a9)
- Adding synthesizer factory to SDK (9af7cb7)
```
apps/backend/src/rhesis/backend/app/database.py
apps/backend/src/rhesis/backend/app/routers/test_set.py
apps/backend/src/rhesis/backend/app/services/test.py
apps/backend/src/rhesis/backend/app/services/test_set.py
apps/backend/src/rhesis/backend/app/utils/crud_utils.py
apps/backend/src/rhesis/backend/app/utils/model_utils.py
apps/backend/src/rhesis/backend/app/utils/uuid_utils.py
apps/backend/src/rhesis/backend/tasks/__init__.py
apps/backend/src/rhesis/backend/tasks/base.py …
```
> Worker Generation

- apps/frontend/src/app/(protected)/test-sets/components/TestSetsGrid.tsx
This PR introduces changes from the `fix/test-set-navigation` branch.
- Fixing test set pagination (5b5e7a4)
```
apps/frontend/src/app/(protected)/test-sets/components/TestSetsGrid.tsx
```
```
5b5e7a4 - Fixing test set pagination (Harry Cruz, 18 seconds ago)
```
> Fix: Test Set Navigation

- apps/backend/src/rhesis/backend/app/services/initial_data.json
- apps/backend/src/rhesis/backend/app/services/organization.py
- apps/backend/src/rhesis/backend/app/utils/crud_utils.py
- apps/frontend/src/components/auth/Auth0Lock.tsx
This PR introduces changes from the `fix/missing-initial-data-metrics-99` branch. This PR addresses issues #99, #96, and #78.
- Hardening initial data login (17d3071)
- Fixing Windows-type authentication (d8fe88a)
- Improving transaction management for initial data. (5226349)
- Removing session commit from individual entries in load initial data (4be2022)
```
apps/backend/src/rhesis/backend/app/services/initial_data.json
apps/backend/src/rhesis/backend/app/services/organization.py
apps/backend/src/rhesis/backend/app/utils/crud_utils.py
apps/frontend/src/components/auth/Auth0Lock.tsx
```
```
17d3071 - Hardening initial data login (Harry Cruz, 2 minutes ago)
d8fe88a - Fixing Windows-type authentication (Harry Cruz, 2 minutes ago)
5226349 - Improving transaction management for initial data. …
```
> Fix: Missing Initial Data Metrics 99

- apps/frontend/src/app/(protected)/endpoints/components/EndpointForm.tsx
- apps/frontend/src/app/(protected)/test-sets/[identifier]/components/TestSetDetailsSection.tsx
- apps/frontend/src/styles/theme.ts
> fixed contrast issues in dark mode

- apps/backend/README.md
- apps/backend/src/rhesis/backend/app/utils/query_validation.py
- docs/backend/odata-guide.md
This PR introduces changes from the `fix/o-data-filtering-validation` branch.
- Updating documentation for odata filtering (4a4171a)
- Fixing validation issues in odata filtering (db045c7)
```
apps/backend/README.md
apps/backend/src/rhesis/backend/app/utils/query_validation.py
docs/backend/odata-guide.md
```
```
4a4171a - Updating documentation for odata filtering (Harry Cruz, 26 seconds ago)
db045c7 - Fixing validation issues in odata filtering (Harry Cruz, 3 minutes ago)
```
> Fix: OData Filtering Validation

- apps/frontend/src/app/(protected)/onboarding/components/OrganizationDetailsStep.tsx
- Fix infinite loop issue where firstName field couldn't be cleared due to repeated prefilling
- Add email detection logic to skip name parsing when session.user.name looks like an email
- Ensure prefilling only happens once during component initialization
- Allow users to properly fill in their names when signing up via email instead of OAuth
Resolves issue where email signup users had their email address parsed as firstName (e.g., 'john.doe@example.com' became 'john.doe' in firstName field) and couldn't clear the field.
Fixes #126
> fix(onboarding): prevent email addresses from being used as first names

- sdk/src/rhesis/sdk/synthesizers/prompt_synthesizer.py
- tests/sdk/synthesizers/prompt_synthesizer/test_prompt_synthesizer.py
- tests/sdk/synthesizers/prompt_synthesizer/test_utils.py
This PR introduces changes from the `feature/document-param-promptsynthesizer-129` branch.
- added documents parameter to PromptSynthesizer and tests (16c5476)
```
sdk/src/rhesis/sdk/synthesizers/prompt_synthesizer.py
tests/sdk/synthesizers/prompt_synthesizer/test_prompt_synthesizer.py
tests/sdk/synthesizers/prompt_synthesizer/test_utils.py
```
```
16c5476 - added documents parameter to PromptSynthesizer and tests (EmanueleDeRossi1, 5 minutes ago)
```
> Document Param Promptsynthesizer 129

- sdk/CONTRIBUTING.md
This PR introduces changes from the `fix/typos-in-sdk-contributing` branch.
- Corrected typos (wrong quotes: “ instead of ") and formatting errors (cfb61be)
```
sdk/CONTRIBUTING.md
```
```
cfb61be - Corrected typos (wrong quotes: “ instead of ") and formatting errors (EmanueleDeRossi1, 34 seconds ago)
```
> Fix: Typos In Sdk Contributing

- .cursor/rules/.cursorrules
- apps/backend/pyproject.toml
- tests/README.md
- tests/backend/README.md
- tests/backend/conftest.py
- tests/backend/test_example_markers.py
- tests/conftest.py
- tests/frontend/README.md
- tests/pytest.ini
- tests/sdk/README.md
This PR introduces changes from the `docs/testing-approach-rhesis` branch.
- Updating Cursor rules (1e9e5be)
- Addng overall test recommendations for Rhesis (70fe933)
- Adding pytest configurations (5e7f77d)
- Adding test markers (79ddb82)
- Adding test recommendations for SDK (cca0d1f)
- Adding general test configurations (5076b6f)
- Adding testing guidance for frontend (601deef)
- Adding testing guidance for backend (6b14d95)
```
.cursor/rules/.cursorrules
apps/backend/pyproject.toml
tests/README.md
tests/backend/README.md
tests/backend/conftest.py
tests/backend/test_example_markers.py
tests/conftest.py
tests/frontend/README.md
tests/pytest.ini
tests/sdk/README.md
```
```
1e9e5be - Updating Cursor rules (Harry Cruz, 80 seconds ago)
70fe933 - Addng overall test recommendations for Rhesis …
```
> Docs/Testing Approach Rhesis

- .gitignore
- apps/backend/CONTRIBUTING.md
- apps/backend/pyproject.toml
- apps/backend/uv.lock
- infrastructure/scripts/db-proxy.sh
This PR introduces changes from the `docs/fix-contributing-guide-backend` branch.
- fix:Adjusting .gitignore for system files macOS (92b473e)
- fix:Adjusting path for macOS compatibility (c99072e)
- chore:Adding dev dependencies (42925ab)
- docs:Updating CONTRIBUTING for macOS (51b8d1b)
- chore:Introducing dev dependencies (014c5ed)
```
.gitignore
apps/backend/CONTRIBUTING.md
apps/backend/pyproject.toml
apps/backend/uv.lock
infrastructure/scripts/db-proxy.sh
```
```
92b473e - fix:Adjusting .gitignore for system files macOS (Emanuele De Rossi, 2 minutes ago)
c99072e - fix:Adjusting path for macOS compatibility (Emanuele De Rossi, 6 minutes ago)
42925ab - chore:Adding dev dependencies (Emanuele De Rossi, 7 minutes ago)
51b8d1b - docs:Updating CONTRIBUTING for macOS (Emanuele De Rossi, 8 …
```
> Docs/Fix Contributing Guide Backend

- .cursor/rules/.cursorrules
- apps/frontend/src/app/(protected)/test-sets/components/TestSetDrawer.tsx
- apps/frontend/src/app/(protected)/test-sets/components/TestSetsCharts.tsx
This PR introduces changes from the `fix/test-set-infinite-loading` branch.
- chore: Added best practice for useEffect in cursor rules. (1d8b378)
- fix: Infinite loading behavior for test sets has been fixed. #64 (4ad89f1)
```
.cursor/rules/.cursorrules
apps/frontend/src/app/(protected)/test-sets/components/TestSetDrawer.tsx
apps/frontend/src/app/(protected)/test-sets/components/TestSetsCharts.tsx
```
```
1d8b378 - chore: Added best practice for useEffect in cursor rules. (Harry Cruz, 3 minutes ago)
4ad89f1 - fix: Infinite loading behavior for test sets has been fixed. #64 (Harry Cruz, 4 minutes ago)
```
> Fix: Test Set Infinite Loading

- .github/create-pr.sh
- CONTRIBUTING.md
- apps/backend/CONTRIBUTING.md
- apps/frontend/CONTRIBUTING.md
This PR introduces changes from the `fix/pr-script-behavior-unpushed` branch.
- docs: Update contributing guides with PR update functionality (d311d54)
- feat: Add PR update functionality for existing pull requests (26df4ff)
- fix: Set upstream tracking when pushing branches (e272ae0)
- fix: Add PR to capitalization abbreviations list (865fbf6)
- docs: Update contributing guides with new PR creation features (e10c577)
- Implement Option 1: Detect and Prompt for unpushed branches/changes (ffa6332)
- fix: Making prepositions and conjunctions not capitalized (4017681)
```
.github/create-pr.sh
CONTRIBUTING.md
apps/backend/CONTRIBUTING.md
apps/frontend/CONTRIBUTING.md
```
```
d311d54 - docs: Update contributing guides with PR update functionality (Harry Cruz, 13 seconds ago)
26df4ff - feat: …
```
> Fix: PR Script Behavior Unpushed

- apps/frontend/src/app/(protected)/test-results/components/BaseTimelineChart.tsx
- apps/frontend/src/app/(protected)/test-results/components/DimensionRadarChart.tsx
- apps/frontend/src/app/(protected)/test-results/components/LatestResultsPieChart.tsx
- apps/frontend/src/app/(protected)/test-results/components/LatestTestRunsChart.tsx
- apps/frontend/src/app/(protected)/test-results/components/MetricTimelineChart.tsx
- apps/frontend/src/app/(protected)/test-results/components/MetricTimelineChartsGrid.tsx
- apps/frontend/src/app/(protected)/test-results/components/PassRateTimelineChart.tsx
- apps/frontend/src/app/(protected)/test-results/components/TestResultsCharts.tsx
- apps/frontend/src/app/(protected)/test-results/components/TestResultsDashboard.tsx
- apps/frontend/src/app/(protected)/test-results/components/TestResultsFilters.tsx
- apps/frontend/src/app/(protected)/test-results/components/TestResultsSummary.tsx
- apps/frontend/src/app/(protected)/test-results/components/timelineUtils.ts
- apps/frontend/src/app/(protected)/test-results/layout.tsx
- apps/frontend/src/app/(protected)/test-results/page.tsx
- apps/frontend/src/components/common/BaseLineChart.tsx
- apps/frontend/src/utils/api-client/interfaces/common.ts
- apps/frontend/src/utils/api-client/interfaces/test-results.ts
- apps/frontend/src/utils/api-client/test-results-client.ts
This PR introduces changes from the `feature/test-results-poc-frontend` branch.
- Comprehensive commit introducing Test Results fucntionality (d86d60b)
- Adding interfaces for handling test results stats (2d28882)
```
apps/backend/src/rhesis/backend/app/routers/services.py
apps/backend/src/rhesis/backend/app/schemas/services.py
apps/backend/src/rhesis/backend/app/services/document_handler.py
apps/backend/src/rhesis/backend/app/services/generation.py
apps/frontend/src/app/(protected)/test-results/components/BaseTimelineChart.tsx
apps/frontend/src/app/(protected)/test-results/components/DimensionRadarChart.tsx
apps/frontend/src/app/(protected)/test-results/components/LatestResultsPieChart.tsx
apps/frontend/src/app/(protected)/test-results/components/LatestTestRunsChart.tsx …
```
> Test Results Poc Frontend

- apps/backend/src/rhesis/backend/app/crud.py
- apps/backend/src/rhesis/backend/app/models/__init__.py
- apps/backend/src/rhesis/backend/app/routers/test_set.py
- apps/frontend/src/app/(protected)/test-results/components/TestResultsDashboard.tsx
- apps/frontend/src/app/(protected)/test-results/components/TestResultsFilters.tsx
- apps/frontend/src/app/(protected)/test-results/components/TestResultsSummary.tsx
- apps/frontend/src/utils/api-client/base-client.ts
- apps/frontend/src/utils/api-client/test-runs-client.ts
- apps/frontend/src/utils/api-client/test-sets-client.ts
This PR introduces changes from the `fix/test-results-display` branch.
```
apps/backend/src/rhesis/backend/app/crud.py
apps/backend/src/rhesis/backend/app/models/__init__.py
apps/backend/src/rhesis/backend/app/routers/test_set.py
apps/frontend/src/app/(protected)/test-results/components/TestResultsDashboard.tsx
apps/frontend/src/app/(protected)/test-results/components/TestResultsFilters.tsx
apps/frontend/src/app/(protected)/test-results/components/TestResultsSummary.tsx
apps/frontend/src/utils/api-client/base-client.ts
apps/frontend/src/utils/api-client/test-runs-client.ts
apps/frontend/src/utils/api-client/test-sets-client.ts
```
```
787d3cc - Adding fixes to test results display (Harry Cruz, 2025-08-08 17:21)
8044579 - Adding filter support for test sets in relation to runs (Harry Cruz, …
```
> Fix: Test Results Display

- apps/backend/src/rhesis/backend/app/routers/services.py
- apps/backend/src/rhesis/backend/app/schemas/services.py
This PR introduces changes from the `feature/add-document-extractor-endpoint-190` branch.
```
apps/backend/src/rhesis/backend/app/routers/services.py
apps/backend/src/rhesis/backend/app/schemas/services.py
```
```
e66e5e4 - feat: add document content extraction endpoint (Emanuele De Rossi, 2025-08-12 17:33)
```
> Add Document Extractor Endpoint

- apps/frontend/src/app/(protected)/tests/new-generated/components/GenerateTestsStepper.tsx
- apps/frontend/src/utils/api-client/interfaces/documents.ts
- apps/frontend/src/utils/api-client/services-client.ts
This PR introduces changes from the `feature/document-upload-auto-metadata-189` branch.
Frontend: Add a new “Upload Documents” step to the Test Generation screen. Automatically generate a title and description from the uploaded content, allow the user to edit both fields, and generate test sets based on the provided documents.
Currently, file uploads are stored only on the local server. When a cloud worker tries to extract content later, it can’t access the local path. To work around this, the process now works as follows:
1. User uploads a file → stored locally
2. Immediately extract content using `/documents/extract` endpoint
3. Generate metadata (name, description) from the content
4. Pass to worker: `documents` array containing:
- name
- description
- content (the extracted text) …
> Document Upload with Automatic Metadata Generation

- apps/backend/src/rhesis/backend/app/routers/test_set.py
- apps/frontend/src/app/(protected)/tests/new-generated/components/GenerateTestsStepper.tsx
- apps/frontend/src/components/common/BaseTag.tsx
This PR introduces changes from the `fix/improve-ux-test-generation-stepper-197` branch. It address frontend issues related to the Test Generation Stepper (outlined in Issue #197), ensuring better user experience and consistency across the component.
```
apps/backend/src/rhesis/backend/app/routers/test_set.py
apps/frontend/src/app/(protected)/tests/new-generated/components/GenerateTestsStepper.tsx
```
```
5e3599d - fix: issue 7. file size validation (Emanuele De Rossi, 2025-08-15 11:19)
29408fb - fix: issue 6. behaviors and topics display in final step (Emanuele De Rossi, 2025-08-15 11:10)
ff99833 - fix: issue 5 – field label naming (Emanuele De Rossi, 2025-08-15 10:07)
1db0727 - fix: issue 4. button label and description (Emanuele De Rossi, 2025-08-14 17:14)
c1a3a61 - fix: handleNext …
```
> Fix: Improve UX/UI Test Generation Stepper

- apps/backend/start.sh
This PR introduces changes from the `fix/update-start-sh-uvicorn` branch.
Updating start.sh to accommodate 'uv run' command to run uvicorn.
```
apps/backend/start.sh
```
```
88ec18b - Update start.sh with uv run for uvicorn (jahanzaibsuleman07, 2025-08-19 10:16)
```
> Fix: Update Start Sh Uvicorn

- apps/frontend/src/app/(protected)/projects/components/ProjectCard.tsx
This PR introduces changes from the `fix/projects-long-project-names-are-truncated-205` branch.
```
apps/frontend/src/app/(protected)/projects/components/ProjectCard.tsx
```
```
6f162bc - truncating project titles (Nicolai Bohn, 2025-08-19 08:30)
```
> Fix: Projects Long Project Names Are Truncated 205

- .github/workflows/frontend.yml
- apps/frontend/Dockerfile
This PR introduces changes from the `fix/frontend-production-mode` branch.
```
.github/workflows/frontend.yml
apps/frontend/Dockerfile
```
```
fd99799 - fix: Missing backeend URL in frontend deployment (Harry Cruz, 2025-08-22 13:55)
43c9eae - fix: Adjusting frontend docker file to production mode (Harry Cruz, 2025-08-22 13:50)
```
> Fix: Frontend PROD Mode

- apps/backend/Dockerfile
This PR introduces changes from the `hotfix/backend-docker-file` branch.
```
apps/backend/Dockerfile
```
```
f38d309 - fix: Adjusting Dockerfile for backend (Harry Cruz, 2025-08-22 14:41)
```
> Hotfix: Backend DOCKER File

- apps/backend/src/rhesis/backend/app/routers/test_run.py
This PR introduces changes from the `fix/test-run-download` branch.
```
apps/backend/src/rhesis/backend/app/routers/test_run.py
```
```
456b074 - fix: remove user-level permission check from test run download endpoint (Harry Cruz, 2025-08-27 08:24)
```
> Fix: Test Run Download

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/task.md
This PR introduces standardized GitHub issue templates for the Rhesis AI repo.
- ✨ `feature_request.md` — structure for proposing new features and improvements
- 🐛 `bug_report.md` — guide for reporting reproducible bugs
- 🛠 `task.md` — template for general engineering or documentation tasks
Standardized issue templates reduce ambiguity, improve communication across the team, and ensure issues are actionable and testable.
- Each template includes examples for clarity
- Optional Gherkin section for behavior-driven test scenarios
- Aligned with company-wide collaboration standards
Resolves #166
> Create standard issue templates for feature, bug, and task #166

- .vscode/settings.json
This PR introduces changes from the `feature/add-testing-to-vs-code-settings` branch.
- exclude .venv directories from search in VS Code
- configure testing configuration that allows testing using VS Code
```
.vscode/settings.json
```
```
5918039 - add testing and exclude .venvs from search (Arkadiusz Kwasigroch, 2025-09-03 16:03)
```
> Add Testing To Vs Code Settings

- sdk/pyproject.toml
- sdk/src/rhesis/sdk/entities/test_set.py
This PR introduces changes from the `task/remove-pyarrow` branch.
```
sdk/pyproject.toml
sdk/src/rhesis/sdk/entities/test_set.py
```
```
14ed13f - remove docs (Arkadiusz Kwasigroch, 2025-09-09 10:51)
0baa964 - remove pyarrow (Arkadiusz Kwasigroch, 2025-09-09 10:49)
efb056b - remove pyarrow (Arkadiusz Kwasigroch, 2025-09-09 10:48)
d966fde - Remove pyarrow dependency to reduce environment and Docker image sizes (Arkadiusz Kwasigroch, 2025-09-09 10:46)
```
> Task/Remove Pyarrow

- apps/frontend/src/app/(protected)/projects/[identifier]/client-wrapper.tsx
This PR introduces changes from the `bug/update_project_header_reactively` branch.
- Project header should reflect the title after editing, immediately without reload.
- Subsequent Project editing should reflect the updated data in the form again without reload.
```
apps/frontend/src/app/(protected)/projects/[identifier]/client-wrapper.tsx
```
```
f15e772 - Update project title/description once edited without reload (jahanzaibsuleman07, 2025-09-12 15:52)
```
> Bug/Update Project Header Reactively

- apps/documentation/app/_meta.js
- apps/documentation/app/sdk/models/page.mdx
- apps/documentation/app/sdk/page.mdx
- sdk/src/rhesis/sdk/models/__init__.py
This PR adds comprehensive documentation for the models functionality in the Rhesis SDK.
- Added detailed models documentation with usage examples and API reference
- Created new SDK documentation pages with interactive examples
- Updated models module with improved imports and functionality
> Models documentation in nextra

- apps/backend/src/rhesis/backend/app/services/invokers/websocket_invoker.py
- tests/backend/conftest.py
- tests/backend/routes/fixtures/entities/projects.py
- tests/backend/routes/fixtures/entities/prompts.py
- tests/backend/routes/fixtures/entities/statuses.py
- tests/backend/routes/fixtures/entities/users.py
- tests/backend/services/test_organization.py
- tests/backend/services/test_test.py
- tests/backend/services/test_test_set.py
- tests/backend/test_crud.py
- tests/backend/utils/test_crud_utils.py
- tests/backend/utils/test_model_utils.py
- tests/pytest.ini
This PR introduces changes from the `feature/test-coverage-maintain-tenant-context` branch.
```
apps/backend/src/rhesis/backend/app/services/invokers/websocket_invoker.py
tests/backend/conftest.py
tests/backend/routes/fixtures/entities/projects.py
tests/backend/routes/fixtures/entities/prompts.py
tests/backend/routes/fixtures/entities/statuses.py
tests/backend/routes/fixtures/entities/users.py
tests/backend/services/__init__.py
tests/backend/services/test_organization.py
tests/backend/services/test_test_set.py
tests/backend/services/test_test.py
tests/backend/test_crud.py
tests/backend/utils/__init__.py
tests/backend/utils/test_crud_utils.py
tests/backend/utils/test_model_utils.py
tests/pytest.ini
```
```
d61640c - tests: Fixing pytest.ini with warn suppression (Harry Cruz, 2025-09-18 …
```
> Test Coverage Maintain Tenant Context

- tests/backend/conftest.py
- tests/backend/fixtures/test_setup.py
- tests/backend/routes/fixtures/data_factories.py
- tests/backend/routes/fixtures/entities/users.py
- tests/backend/routes/test_response_pattern.py
- tests/backend/routes/test_risk.py
Adding obfuscation for test logging.
> tests: Fixing tests and fixtures

- apps/frontend/src/app/(protected)/dashboard/components/DashboardCharts.tsx
This PR improves the dashboard charts by integrating real test results data and fixing the cumulative tests display issue.
- Fixed the "Total Tests" chart to properly show cumulative totals over time
- Updated chart title to "Cumulative Tests" for better clarity
- Added logic to ensure the most recent month displays the actual current total (32,408) instead of incomplete historical data
- Added fallback handling when no historical data is available
- Integrated real test results API data for the execution trend chart
- Replaced mock data with actual timeline data from test results
- Added parallel API calls for better performance using Promise.all
- Enhanced chart with proper color theming (primary blue, success green, error red)
- Added chronological sorting and proper date formatting
- …
> fix(dashboard): improve dashboard charts with real data and cumulative totals

- apps/frontend/src/app/(protected)/test-runs/[identifier]/components/TestRunTestsGrid.tsx
- apps/frontend/src/app/(protected)/test-runs/components/TestRunsGrid.tsx
- apps/frontend/src/app/(protected)/test-sets/components/TestSetsGrid.tsx
- apps/frontend/src/app/(protected)/tests/components/TestsGrid.tsx
- apps/frontend/src/utils/api-client/interfaces/test-run.ts
This PR introduces changes from the `feat/restore-counts-functionality` branch.
```
apps/frontend/src/app/(protected)/test-runs/[identifier]/components/TestRunTestsGrid.tsx
apps/frontend/src/app/(protected)/test-runs/components/TestRunsGrid.tsx
apps/frontend/src/app/(protected)/test-sets/components/TestSetsGrid.tsx
apps/frontend/src/app/(protected)/tests/components/TestsGrid.tsx
apps/frontend/src/utils/api-client/interfaces/test-run.ts
```
```
38e2e57e - fix: resolve linting errors and formatting issues (jahanzaibsuleman07, 2025-09-30 15:08)
bb21ce36 - feat: add comments and tasks count columns to entity DataGrids (jahanzaibsuleman07, 2025-09-26 13:13)
```
> Feat/Restore Counts Functionality

- apps/backend/src/rhesis/backend/app/routers/services.py
This PR introduces changes from the `fix/missing-tentant-db-session` branch.
```
apps/backend/src/rhesis/backend/app/routers/services.py
```
```
2bba5779 - fix: add missing import for get_tenant_db_session in services router (Harry Cruz, 2025-10-02 15:40)
```
> Fix: Missing Tentant Db Session

- apps/backend/src/rhesis/backend/app/crud.py
- apps/backend/src/rhesis/backend/app/routers/endpoint.py
- apps/backend/src/rhesis/backend/app/routers/test.py
- apps/backend/src/rhesis/backend/app/routers/test_configuration.py
- apps/backend/src/rhesis/backend/app/routers/test_result.py
- apps/backend/src/rhesis/backend/app/routers/test_set.py
- apps/backend/src/rhesis/backend/app/routers/user.py
- apps/backend/src/rhesis/backend/app/services/test_run.py
- apps/backend/src/rhesis/backend/app/services/test_set.py
- apps/backend/src/rhesis/backend/tasks/example_task.py
- apps/backend/src/rhesis/backend/tasks/execution/modes.py
- apps/backend/src/rhesis/backend/tasks/execution/parallel.py
- apps/backend/src/rhesis/backend/tasks/execution/results.py
- apps/backend/src/rhesis/backend/tasks/execution/run.py
- apps/backend/src/rhesis/backend/tasks/execution/shared.py
- apps/backend/src/rhesis/backend/tasks/execution/test.py
- apps/backend/src/rhesis/backend/tasks/execution/test_execution.py
- apps/backend/src/rhesis/backend/tasks/test_configuration.py
- apps/backend/src/rhesis/backend/tasks/test_set.py
- apps/backend/src/rhesis/backend/tasks/utils.py
- apps/frontend/next-env.d.ts
- apps/frontend/package-lock.json
- apps/frontend/package.json
- chord_execution_investigation_summary.md
This PR introduces changes from the `fix/test-run-issues/v0.3.0` branch.
```
apps/backend/src/rhesis/backend/app/crud.py
apps/backend/src/rhesis/backend/app/routers/endpoint.py
apps/backend/src/rhesis/backend/app/routers/test.py
apps/backend/src/rhesis/backend/app/routers/test_configuration.py
apps/backend/src/rhesis/backend/app/routers/test_result.py
apps/backend/src/rhesis/backend/app/routers/test_set.py
apps/backend/src/rhesis/backend/app/routers/user.py
apps/backend/src/rhesis/backend/app/services/test_run.py
apps/backend/src/rhesis/backend/app/services/test_set.py
apps/backend/src/rhesis/backend/tasks/example_task.py
apps/backend/src/rhesis/backend/tasks/execution/modes.py
apps/backend/src/rhesis/backend/tasks/execution/parallel.py …
```
> Fix: Test Run Issues/V0.3.0

- apps/backend/src/rhesis/backend/app/auth/user_utils.py
- apps/backend/src/rhesis/backend/app/crud.py
- apps/backend/src/rhesis/backend/app/routers/auth.py
- apps/backend/src/rhesis/backend/app/routers/organization.py
- apps/backend/src/rhesis/backend/app/routers/user.py
- apps/backend/src/rhesis/backend/app/services/organization.py
- apps/backend/src/rhesis/backend/app/services/stats/calculator.py
- apps/backend/src/rhesis/backend/app/services/stats/common.py
- apps/backend/src/rhesis/backend/app/services/stats/test_run.py
- apps/backend/uv.lock
- apps/frontend/src/utils/session.ts
This PR introduces changes from the `fix/onboarding-issues/v0.3.0` branch.
```
apps/backend/src/rhesis/backend/app/auth/user_utils.py
apps/backend/src/rhesis/backend/app/crud.py
apps/backend/src/rhesis/backend/app/routers/auth.py
apps/backend/src/rhesis/backend/app/routers/organization.py
apps/backend/src/rhesis/backend/app/routers/user.py
apps/backend/src/rhesis/backend/app/services/organization.py
apps/backend/src/rhesis/backend/app/services/stats/calculator.py
apps/backend/src/rhesis/backend/app/services/stats/common.py
apps/backend/src/rhesis/backend/app/services/stats/test_run.py
apps/backend/uv.lock
apps/frontend/src/utils/session.ts
```
```
98b77516 - feat(onboarding): enhance test set initialization during data loading (Harry Cruz, 2025-10-04 15:47)
476a7991 - fix(stats): resolve …
```
> Fix: Onboarding Issues/V0.3.0

- sdk/src/rhesis/sdk/metrics/utils.py
This PR introduces changes from the `fix/pull-metrics` branch.
```
sdk/src/rhesis/sdk/metrics/utils.py
```
```
97b052f8 - fix: pull metrics error (Arkadiusz Kwasigroch, 2025-10-06 09:56)
```
> Fix: Pull Metrics

- apps/frontend/src/app/(protected)/test-runs/components/TestRunsGrid.tsx
This PR introduces changes from the `fix/flicking-test-runs-grid` branch.
```
apps/frontend/src/app/(protected)/test-runs/components/TestRunsGrid.tsx
```
```
db56c437 - fix(test-runs): resolve flickering data grid on test runs page (Harry Cruz, 2025-10-06 21:28)
```
> Fix: Flicking Test Runs Grid

- .github/workflows/lint.yml
This PR introduces changes from the `fix/fix-linting-workflow-behavior` branch.
```
.github/workflows/lint.yml
```
```
6dcd840c - refactor: optimize lint workflow with conditional execution and single checkout (Harry Cruz, 2025-10-07 15:11)
```
> Fix: Fix Linting Workflow Behavior

- apps/backend/src/rhesis/backend/app/crud.py
- apps/backend/src/rhesis/backend/app/routers/token.py
- apps/backend/src/rhesis/backend/app/schemas/test.py
- tests/backend/security/test_organization_filtering.py
This PR introduces changes from the `fix/token-display-backend-issues` branch.
```
apps/backend/src/rhesis/backend/app/crud.py
apps/backend/src/rhesis/backend/app/routers/token.py
apps/backend/src/rhesis/backend/app/schemas/test.py
tests/backend/security/test_organization_filtering.py
```
```
25206512 - test(security): add token organization filtering tests (Harry Cruz, 2025-10-08 16:50)
ed85b2c5 - fix(tokens): add organization filtering and accurate token count (Harry Cruz, 2025-10-08 16:50)
57ed718a - fix(schemas): migrate Source schema to Pydantic V2 ConfigDict (Harry Cruz, 2025-10-08 16:49)
```
> Fix: Token Display Backend Issues
